version: '3.8'
services:
  idgenerator:
    container_name: node_api
    restart: on-failure
    environment:
      - NODE_ENV=production
    build:
        context: ./
    volumes:
      - ./src:/app/src
    expose:
      - "4000"
    command: >
      sh -c "yarn start"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - idgenerator
    ports:
      - "5000:5000"
